# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm start
    networks:
      - rest1-network

  mongo:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    networks:
      - rest1-network
    volumes:
      - ./data/db:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password      


  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - rest1-network
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

networks:
  rest1-network:
    external: true


#docker exec -it jobs-php-fpm /bin/bash

  #find /application/ -type f -exec chmod 644 {} \;
  #find /application -type d -exec chmod 755 {} \;
  #chown -R 1000:1000 /application/
  #chmod -R 777 /application/storage
  #chmod -R 777 /application/bootstrap/cache/
  #chmod -R 777 /application/public/js/builds
  #kompose convert -f docker-compose.yml    
  #npm run list -- --init   

